### ISSUE TITLE
Example run on reCOGnizer output

### ISSUE THREAD

**Issue by davidecrs** [iquasere/KEGGCharter#12]
Hi, 

is it possible to run `keggcharter` on `reCOGnizer` output files?

If yes, can you show an example code?

Best,
Davide

**Comment by iquasere** [comment]
Greetings! 

Starting with reCOGnizer, you can download the [exemplary FASTA](https://github.com/iquasere/reCOGnizer/blob/master/ci/proteomes.fasta) and annotate with 
```
recognizer -f proteomes.fasta -o recognizer_output
```

You should obtain a file with EC numbers information, use it as input for KEGGCharter
```
keggcharter -f recognizer_output/reCOGnizer_results.tsv -ecc 'EC number' -o keggcharter_output -it "My taxonomy" -iq
```

These commands will represent the EC numbers identified by reCOGnizer in the 250 default maps of KEGGCharter. The identified functions will be coloured in grey, and the legend will only say "My taxonomy". If you have taxonomic or quantification information, you can use it to represent more complex maps, replacing the `-iq` and `-it` by the appropriate parameters.

**Comment by davidecrs** [comment]
Hi @iquasere ,

thanks for your answer, I'll try that.
