### ISSUE TITLE
Invalid file format now after implementation of regex checks

### ISSUE THREAD

**Issue by amcomeau** [iquasere/KEGGCharter#15]
Hello again, so soon! My input file is now not working as of the new version 1.1.0 due to the newly implemented regex checks - this is the same file I was using just a few days ago (same EC numbers, just summed qcols instead of individual ones) and so must be the syntax for the regex.

Perhaps in the EC# check you are not allowing any letters, when provisional EC#s do have "n1" (for example), which was working before you put the check in. The input file I'm using is attached. Thanks!

[MirallesMetaG-unstrat-matrix-RPKM_finalTypeSortAndSummed-forKEGGCharter.txt](https://github.com/iquasere/KEGGCharter/files/13824550/MirallesMetaG-unstrat-matrix-RPKM_finalTypeSortAndSummed-forKEGGCharter.txt)

**Comment by iquasere** [comment]
I forgot about those EC numbers... only accounted for dashes `-`. Guess `1.1.1` version is coming right next

**Comment by iquasere** [comment]
Should be fixed now. Sorry about that, went a bit ham on the regexes and made them too restrictive. The regex of KEGG IDs was also inadequate.

[`KEGGCharter 1.1.1`](https://github.com/iquasere/KEGGCharter/releases/tag/1.1.1) now fixes that, and can already be installed.

**Comment by amcomeau** [comment]
Everything seems to be working now, thanks! I'll let you know if anything else pops up!
