### ISSUE TITLE
import error after install 

### ISSUE THREAD

**Issue by Ethnobotaniker** [iquasere/KEGGCharter#17]
Hello, 
i just installed keggcharter in a clean conda enviroment and cant run it.
The enviroment i installed it in is active and when i try to run it with " keggcharter -h" i get the following output: 

``
/home/lfuernwein/.conda/envs/keggcharter/bin/keggcharter:9: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd
Traceback (most recent call last):
  File "/home/lfuernwein/.conda/envs/keggcharter/bin/keggcharter", line 23, in <module>
    from keggpathway_map import KEGGPathwayMap, expand_by_list_column
  File "/home/lfuernwein/.conda/envs/keggcharter/share/keggpathway_map.py", line 9, in <module>
    from matplotlib import pyplot as plt, colors, colormaps
ImportError: cannot import name 'colormaps' from 'matplotlib' (/home/lfuernwein/.conda/envs/keggcharter/lib/python3.10/site-packages/matplotlib/__init__.py)
``

I installed it as follows:
``
conda create -n keggcharter 
``
``
conda activate keggcharter
``
``
conda install -c conda-forge -c bioconda keggcharter
``
i would appreciate your help and thank you in advance.

**Comment by iquasere** [comment]
Hi @Ethnobotaniker ! Sorry for taking so long to respond, had a long vacation these last weeks.

It seems the `matplotlib` package is not available in your environment. Could you please try running `conda install conda-forge::matplotlib` and run the KEGGCharter command again?

**Comment by Ethnobotaniker** [comment]
No problem thanks for your reply.
I just looked at the installed packages and it seems like only `matplotlib-base`   was installed in the environment.
After installing `matplotlib`  i now can call the help page and it seems its installed properly now.

**Comment by iquasere** [comment]
Thank you for raising attention to this, I'll have to update the recipe at Bioconda to include the full matplotlib. It was a mistake on my end, thought `matplotlib-base` was enough
