### ISSUE TITLE
could not download resources 

### ISSUE THREAD

**Issue by GaioTransposon** [iquasere/KEGGCharter#3]
Hi Joao, 

thanks for creating reCOGnizer and KeggCharter. 

My command: 
`keggcharter.py -f test.tsv -tcol "value" -koc "KO" -tc "Taxonomic lineage (GENUS)" -gcol "gcol" -o test_out -mm "Methane metabolism"`

My output: 
```
2022-07-27 11:30:36: Creating KEGG Pathway representations for 1 metabolic pathways.
Some resources were not found for map [koMethane metabolism]! Going to download them
Could not download resources for [koMethane metabolism]!
Analysis of map Methane metabolism failed!
KEGGCharter analysis finished in 00h00m59s
```

Could you tell what is happening? Why is it attempting downloading and failing? I installed keggcharter through conda. 

Kind Regards
Dany

**Comment by iquasere** [comment]
Hi there, Dany! Thank you for raising attention to this! It's really weird that KEGGCharter is trying to download "koMethane metabolism", seems like a strange concatenation bug. If this and #4 are problems that come from the same inputs, I'll try to tackle them here. Could you send me your input that provokes this behavior from KEGGCharter? Also, what is the version you are running?

**Comment by GaioTransposon** [comment]
this specific issue was solved by using the code respective to the metabolism: 
`keggcharter.py -f test.tsv -tcol "value" -koc "KO" -tc "Taxonomic lineage (GENUS)" -gcol "gcol" -o test_out2 -mm 00680` 
```
2022-08-10 13:34:54: Creating KEGG Pathway representations for 1 metabolic pathways.
2022-08-10 13:34:54: [1/1] Methane metabolism
KEGGCharter analysis finished in 00h01m23s
```
