### ISSUE TITLE
nonexplicit  error message 

### ISSUE THREAD

**Issue by GaioTransposon** [iquasere/KEGGCharter#5]
Hi Joao, 

If the gcol is not given:
`keggcharter.py -f MOSCA_Entry_Report.xlsx -keggc "Cross-reference (KEGG)" -tcol mt_0.01a_normalized ` 
This is the message: 
```
2022-08-10 12:52:48: Arguments valid.
2022-08-10 12:53:03: Data successfully read.
Converting 16059 KEGG IDs to KOs through the KEGG API: 100%|████████████████████████████████████████████████████████████████████████████████| 108/108 [02:26<00:00,  1.36s/it]
Converting 2416 KOs to EC numbers through the KEGG API: 100%|█████████████████████████████████████████████████████████████████████████████████| 17/17 [00:20<00:00,  1.19s/it]
2022-08-10 12:55:52: Results saved to KEGGCharter_results/KEGGCharter_results.tsv
Traceback (most recent call last):
  File "/shared/homes/152324/miniconda3/envs/keggcharter_env/bin/keggcharter.py", line 451, in <module>
    main()
  File "/shared/homes/152324/miniconda3/envs/keggcharter_env/bin/keggcharter.py", line 415, in main
    args.genomic_columns = args.genomic_columns.split(',')
AttributeError: 'NoneType' object has no attribute 'split'
```
Not really intuitive. It should just say "gcol is missing"

**Comment by iquasere** [comment]
Submitted a new version - 0.3.5 - which will soon be available. Do check if this has been improved

**Comment by GaioTransposon** [comment]
Installed the new version (0.4.1) and this now happens: 

`keggcharter.py -f reCOGnizer_results.tsv -o test -ecc "EC number" -mm "Fatty acid metabolism"`

```
Created /shared/homes/152324/miniconda3/envs/keggcharter_env/bin/kc_kgmls
Created /shared/homes/152324/miniconda3/envs/keggcharter_env/bin/kc_csvs
2022-12-14 14:21:48: Arguments valid.
/shared/homes/152324/miniconda3/envs/keggcharter_env/bin/keggcharter.py:117: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  return pd.read_csv(file, sep='\t')
2022-12-14 14:22:16: Data successfully read.
Converting 1703 EC numbers to KOs through the KEGG API: 100%|███████████████████████████████████████████████████████████████████| 12/12 [00:13<00:00,  1.16s/it]
Converting 2365 KOs to EC numbers through the KEGG API: 100%|█████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:17<00:00,  1.08s/it]
2022-12-14 14:25:27: Results saved to test/KEGGCharter_results.tsv
Traceback (most recent call last):
  File "/shared/homes/152324/miniconda3/envs/keggcharter_env/bin/keggcharter.py", line 489, in <module>
    main()
  File "/shared/homes/152324/miniconda3/envs/keggcharter_env/bin/keggcharter.py", line 437, in main
    args.genomic_columns = args.genomic_columns.split(',')
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'
```
I don't have in this case a genomic column. As it is optional, keggcharter.py should not be complaining about it, right?

**Comment by iquasere** [comment]
KEGGCharter always counts on one column of taxonomy and another of quantification to build the maps for. In KEGGCharter, this information can be inputted alternatively using the ```-it NAME_OF_TAXONOMY``` and ```-iq``` parameters, which will input taxonomy and quantification, respectively, replace the ```-tc``` and ```-gcols```/```-tcols``` parameters. ```-it``` requires NAME_OF_TAXONOMY as it is the value that will appear represented in the maps.

As you had complained before, this is not intuitively expressed in the interface. I will update when I have the time.

**Comment by Calvin2077** [comment]
Hello quick question is quantification mandatory for the use of KEGGCharter or is there a way to make this data optional as currently my lab can't obtain quantification levels of our proteins?

Thank you very much.

**Comment by iquasere** [comment]
You can input a mock quantification with the ```-iq``` parameter. In the future, I hope to make this more intuitive.
