### ISSUE TITLE
abundance info

### ISSUE THREAD

**Issue by GaioTransposon** [iquasere/KEGGCharter#7]
Hi Joao, 

1. I might have missed this, but why is there more than 1 column for abundance? 
example: -mgc mg_column1,mg_column2

2. also, does KeggCharter expect it to be normzalized by sample size or does it expect raw abundance info? 

3. is it possible to skip giving abundance and taxa info, and still get a png on a specific metabolic pathway from keggcharter? 

Kind Regards
Dany

**Comment by iquasere** [comment]
I explained it in the other issue, but also post here the [link](https://github.com/iquasere/KEGGCharter#mock-imputation-of-quantification-and-taxonomy) to the documentation about this.

There is still a lot of work to be put in KEGGCharter, unfortunately it hasn't been my priority these last months...
