### ISSUE TITLE
Help with multiple Genomes

### ISSUE THREAD

**Issue by Calvin2077** [iquasere/KEGGCharter#8]
Hello!

I was wondering if I could please have some help in that I want to create metabolism maps for the genomes of multiple archaea.

While I got the program to work great! The problem I am having is that the maps only show that one species has a specific gene/enzyme (via a particular colour); however, when I access my excel document, my other species also have this gene. 

For example, for gene EO 4.2.1.3, both of my practice genomes have these genes, but when I create metabolic maps, only one colour comes up (suggestive that only one genome has it). However, strange enough, sometimes I do get a split of two colours (hence saying that both genomes have this gene)  for some genes in some pathways, but this isn't always the case.

Therefore, if I could please have some help, it would be greatly appreciated.  
  
here is my code 
 keggcharter.py -f Book223.xlsx --input-quantification -koc "KO_column" -tc "Taxonomic lineage (SPECIES)" -o pratice25
  
And my excel 
[Book223.xlsx](https://github.com/iquasere/KEGGCharter/files/10378308/Book223.xlsx)

Thank you very much

**Comment by iquasere** [comment]
Hey there!

It is important to note that KEGG Orthologs (KOs, the ID used to relate functional information in the maps) denote reactions, not ECs or genes. Therefore, it is possible that an EC will show up on the box and not be represented for an enzyme that supposedly has it. 

Information in KEGG, unfortunately, is still very incomplete. An an example, many maps still lack a consider ammount of information for certain boxes, and therefore the KEGG API doesn't provide functionality to those boxes (which in KEGGCharter stay white). This is not the case here, and so I'll investigate if something is wrong.

> For example, for gene EO 4.2.1.3, both of my practice genomes have these genes, but when I create metabolic maps, only one colour comes up

Could you tell me what map is causing this? Even better if you can send me the output of KEGGCharter (the PNG map).

**Comment by Calvin2077** [comment]
Hello!

Thank you for getting back to me so quickly; it is much appreciated and means a lot.

Also, thank you very much for telling me all of this information; it is much appreciated and has helped with my understanding of KEGG, so I appreciate it. 

Regarding my problem, I have attached two example png files. The first ("potential_Citrate cycle (TCA cycle)_one_species") shows the citric acid cycle for one species of Archaea (gargensis) in green; however, when I then run keggcharter.py using two species (gargensis/green and viennensis/orange) ("potential_Citrate cycle (TCA cycle)_two_species"), the map shows that only the second species (in orange) has these reactions.   

![potential_Citrate cycle (TCA cycle)_one_species](https://user-images.githubusercontent.com/72618537/211606784-a9e2996a-ecbc-492a-9b01-0ccca9ea041b.png)
![potential_Citrate cycle (TCA cycle)_two_species](https://user-images.githubusercontent.com/72618537/211606786-b95ebe53-2c12-416a-a142-0dc1fdd9cba5.png)

**Comment by iquasere** [comment]
This has nothing to do with KEGG, does look like a very bad bug on KEGGCharter's part. I'll try to reproduce the bug on my end, see what is causing and fix it.

Thank you for raising attention to this issue!

**Comment by Calvin2077** [comment]
Awesome thank you very much, and I am sorry to hear it is a bug. But thank you very much for working on it, it is much appreciated. And if I can be of any assistance please let me know!

**Comment by iquasere** [comment]
I found it. It was a very badly made ```if else``` clause. 

The effects of this bug were that organisms that should not be represented were being represented, if they were the first ones for a certain box. For the map you sent, KEGGCharter now represents no genomic potential. 

![potential_Citrate cycle (TCA cycle)](https://user-images.githubusercontent.com/16226371/213174830-f97480ee-68de-44e4-be2a-6e8842d8e803.png)

Even though in most autotrophic bacteria and anaerobic archaea the TCA cycle operates in a reductive, biosynthetic direction, since we are talking of the TCA cycle here, were these Archaea supposed to be represented in the map? 

If so, I might relax the obligation of showing up on KEGG's taxonomy KGMLs, since those might be severely incomplete. KEGGCharter uses the taxonomic maps from KEGG to trim functions that are wrongly attributed to organisms because of promiscuity in KOs, and such restriction could be hiding some functions. Nevertheless, wil need to test this carefully.

Version ```0.4.2``` will soon be launched, taking care of this bug. If you find the taxonomic KGMLs are hurting analysis, please don't hesitate raising a new issue.

**Comment by Calvin2077** [comment]
Hello,

Fantastic! Thank you very much for finding and solving this problem; it is very much appreciated.

Regarding your questions, a lot of the archaea species I am working with have either the complete or a mostly complete TCA cycle (missing 1 or 2 enzymes, but we hypothesize they are using an unknown homologue or an unknown enzyme to complete the cycle. 

At this time, we don't know what they are using the TCA cycle for, but hopefully, with time we can help answer this. Thanks again for all your help it is much appreciated.

**Comment by iquasere** [comment]
Then, it seems KEGG has more missing information that I thought. Might add an option to ignore the taxa specific KGMLs in the future.

**Comment by Calvin2077** [comment]
Awesome thank you very much! If I can ask, what will be the timeline for this new feature?

**Comment by iquasere** [comment]
This is a single-person project, so might do it right tomorrow, if it is helpful for your work.

**Comment by Calvin2077** [comment]
It will be of great help for my projects please and thank you, however if you need some more time to work on it I absolutely  understand and there is no immediate rush. Thank you very much.
