### ISSUE TITLE
question about transforming KO IDs and losing data

### ISSUE THREAD

**Issue by nicolazarte** [iquasere/KEGGCharter#9]
Hi, 
I noticed that many of the IDs I wanted to map weren't included in the map, I think the reason is that in the conversion step of KO's many are lost. Why If I have already gave a KO column your program generates an "KO (KEGGCharter)" column in the results.tsv and use those to fill the map instead of the original column?

Here are the first rows of the KEGGCharter_results.tsv to explain myself better.

Genome | Gene ID | KO | KO (KEGGCharter)
-- | -- | -- | --
CK1 | HJENIJGG_00001 | K02625 |  
CK1 | HJENIJGG_00001 | K03761 |  
CK1 | HJENIJGG_00002 | K05811 |  
CK1 | HJENIJGG_00003 | K00998 | K00998,K17103
CK1 | HJENIJGG_00004 | K09181 |  
CK1 | HJENIJGG_00005 | K05812 |  
CK1 | HJENIJGG_00006 | K03672 |  
CK1 | HJENIJGG_00007 | K03214 |  
CK1 | HJENIJGG_00008 | K03648 | K21929,K03648,K25266
CK1 | HJENIJGG_00009 | K06866 |  
CK1 | HJENIJGG_00010 | K05590 | K12647,K12823,K12835,K13185,K17678,K14326,K17820,K17043,K12813,K25022,K11594,K18422,K18432,K12858,K11273,K14808,K13983,K03732,K14810,K13117,K05592,K20099,K03724,K25328,K18995,K14777,K18409,K16911,K21869,K13178,K05590,K14780,K13177,K12820,K13182,K12814,K13183,K12649,K18408,K26077,K03579,K21505,K22273,K12818,K17679,K12646,K11701,K19466,K18994,K12598,K13026,K14778,K20096,K03578,K05591,K13179,K14806,K14807,K12614,K26394,K14442,K12811,K18655,K13181,K13982,K14779,K18711,K17675,K14809,K13116,K14776,K12812,K14805,K12815,K11927,K18664,K14433,K19036,K13131,K18656,K17642,K13025,K14811,K20103,K26438,K18692,K13184,K17265,K14781,K12854,K20101,K12599
CK1 | HJENIJGG_00011 | K15460 |  
CK1 | HJENIJGG_00012 | K00278 |  
CK1 | HJENIJGG_00013 | K03088 |  
CK1 | HJENIJGG_00014 | K03597 |  
CK1 | HJENIJGG_00015 | K03598 |  
CK1 | HJENIJGG_00016 | K03803 |  
CK1 | HJENIJGG_00017 | K03596 |  
CK1 | HJENIJGG_00018 | K03100 |  

For instance, I wanted to draw the map m00910, Nitrogen metabolism. One of the many missing enzymes on the map that I have in the table is K00363, which is correctly converted to EC 1.7.1.15, but nonetheless in the map the corresponding box is left unfilled.

If I use the original KEGG Mapper I get the map with all the KOs correctly charted, but I liked the functionality of your software of being able to draw multiple genomes in a map. Thanks for your work.

**Comment by iquasere** [comment]
Hey there! Thank you very much for reporting on this!

By your description, it does seem like a problem with KEGGCharter. Do note that, if inputting taxonomic information through the command line, KEGGCharter will obtain taxonomic specific information that will trim the KOs that are not present on each specific taxon.

Could you please provide some input file and command to reproduce this?

Also, are you using the latest version - ```0.5```?

**Comment by iquasere** [comment]
Please check if this issue persists in version `0.6`. If so, don't hesitate reopening the issue.
